modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="noahsmineralmod" #mandatory
version="0.0.1" #mandatory
displayName="Noah's Mineral Mod" #mandatory
displayURL="http://example.com/" #optional
logoFile="logo.png" #optional
authors="XxN04hWL4MBxX" #optional
description='''
Alpha 0.0.1
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
