modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
[[mods]] #mandatory
modId="noahsmineralmod" #mandatory
version="0.0.1" #mandatory
displayName="Noah's Mineral Mod" #mandatory
displayURL="https://bit.ly/39u9nCw" #optional
logoFile="logo.png" #optional
authors="AcidApple2006" #optional
description='''
Alpha 0.0.1
'''
[[dependencies.noahsmineralmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.noahsmineralmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"